
export enum Tool {
  GENERATE = 'generate',
  EDIT = 'edit',
}

export interface ImageData {
  base64: string;
  mimeType: string;
}

export type AspectRatio = 'Default' | '1:1' | '16:9' | '9:16' | '4:3' | '3:4';

export type ImageGenerationModel = 'imagen-4.0-generate-001' | 'gemini-2.5-flash-image';

export interface ArtStyle {
  id: number;
  name: string;
  category: string;
  prompt: string;
}

export const artStyles: ArtStyle[] = [
    // ESTILOS ARTÍSTICOS TRADICIONALES (40)
    { id: 1, name: "Acuarela", category: "Tradicional", prompt: "watercolor painting, soft brushstrokes, translucent colors, flowing gradients, dreamy aesthetic" },
    { id: 2, name: "Óleo", category: "Tradicional", prompt: "oil painting, rich textures, layered brushstrokes, visible paint strokes, classical art style" },
    { id: 3, name: "Impresionismo", category: "Tradicional", prompt: "impressionist style, loose brushwork, vibrant colors, capturing light, outdoor scenes, painted plein air" },
    { id: 4, name: "Expresionismo", category: "Tradicional", prompt: "expressionist art, bold colors, distorted forms, emotional intensity, dramatic brushstrokes" },
    { id: 5, name: "Surrealismo", category: "Tradicional", prompt: "surrealist art, dreamlike imagery, impossible scenarios, melting objects, subconscious themes" },
    { id: 6, name: "Cubismo", category: "Tradicional", prompt: "cubist style, geometric shapes, fragmented forms, multiple perspectives, abstract composition" },
    { id: 7, name: "Art Nouveau", category: "Tradicional", prompt: "art nouveau style, flowing lines, organic forms, ornate details, elegant curves, decorative elements" },
    { id: 8, name: "Art Deco", category: "Tradicional", prompt: "art deco style, geometric patterns, bold colors, luxurious aesthetic, streamlined forms, golden accents" },
    { id: 9, name: "Puntillismo", category: "Tradicional", prompt: "pointillism technique, small dots of color, optical color mixing, detailed texture, impressionist influence" },
    { id: 10, name: "Gouache", category: "Tradicional", prompt: "gouache painting, matte finish, opaque colors, flat areas of color, illustrative quality" },
    { id: 11, name: "Pastel", category: "Tradicional", prompt: "pastel art, soft colors, chalky texture, gentle blending, delicate strokes, powdery finish" },
    { id: 12, name: "Tinta China", category: "Tradicional", prompt: "ink wash painting, Chinese brush painting, flowing black ink, minimalist composition, zen aesthetic" },
    { id: 13, name: "Fresco", category: "Tradicional", prompt: "fresco painting, wall mural style, aged texture, renaissance aesthetic, classical composition" },
    { id: 14, name: "Grabado", category: "Tradicional", prompt: "engraving style, crosshatching, fine lines, high contrast, woodcut aesthetic, detailed linework" },
    { id: 15, name: "Litografía", category: "Tradicional", prompt: "lithograph print, grainy texture, limited color palette, vintage poster style" },
    { id: 16, name: "Collage", category: "Tradicional", prompt: "collage art, mixed media, cut paper, layered textures, assembled elements, contemporary" },
    { id: 17, name: "Carboncillo", category: "Tradicional", prompt: "charcoal drawing, smudged blacks, dramatic shadows, sketchy quality, high contrast" },
    { id: 18, name: "Serigrafía", category: "Tradicional", prompt: "screen print, bold flat colors, pop art aesthetic, graphic quality, limited palette" },
    { id: 19, name: "Aerógrafo", category: "Tradicional", prompt: "airbrush art, smooth gradients, photorealistic details, glossy finish, 80s aesthetic" },
    { id: 20, name: "Pintura al Temple", category: "Tradicional", prompt: "tempera painting, luminous colors, egg tempera technique, medieval manuscript style" },
    { id: 21, name: "Miniatura Persa", category: "Tradicional", prompt: "persian miniature, intricate details, flat perspective, rich colors, ornate patterns, gold leaf accents" },
    { id: 22, name: "Ukiyo-e", category: "Tradicional", prompt: "ukiyo-e woodblock print, japanese art, bold outlines, flat colors, traditional patterns" },
    { id: 23, name: "Batik", category: "Tradicional", prompt: "batik art, wax-resist dyeing, indonesian patterns, vibrant colors, organic flowing designs" },
    { id: 24, name: "Iconografía Bizantina", category: "Tradicional", prompt: "byzantine icon, gold background, religious imagery, flat perspective, solemn faces" },
    { id: 25, name: "Pintura Rupestre", category: "Tradicional", prompt: "cave painting, primitive art, earth tones, simple figures, ancient aesthetic, rock texture" },
    { id: 26, name: "Manuscrito Iluminado", category: "Tradicional", prompt: "illuminated manuscript, medieval art, gold leaf, intricate borders, religious themes" },
    { id: 27, name: "Pintura Renacentista", category: "Tradicional", prompt: "renaissance painting, classical composition, sfumato technique, realistic proportions, chiaroscuro lighting" },
    { id: 28, name: "Barroco", category: "Tradicional", prompt: "baroque art, dramatic lighting, rich colors, dynamic composition, ornate details" },
    { id: 29, name: "Rococó", category: "Tradicional", prompt: "rococo style, pastel colors, delicate ornaments, playful themes, elegant curves" },
    { id: 30, name: "Neoclasicismo", category: "Tradicional", prompt: "neoclassical art, greek and roman inspired, symmetrical composition, heroic themes" },
    { id: 31, name: "Romanticismo", category: "Tradicional", prompt: "romantic art, dramatic landscapes, emotional intensity, sublime nature, heroic subjects" },
    { id: 32, name: "Realismo", category: "Tradicional", prompt: "realist art, accurate depiction, everyday scenes, natural lighting, social commentary" },
    { id: 33, name: "Pre-Rafaelita", category: "Tradicional", prompt: "pre-raphaelite style, detailed nature, vibrant colors, medieval themes, romantic subjects" },
    { id: 34, name: "Simbolismo", category: "Tradicional", prompt: "symbolist art, mystical themes, dreamlike imagery, hidden meanings, spiritual subjects" },
    { id: 35, name: "Fauvismo", category: "Tradicional", prompt: "fauvist style, wild colors, bold brushstrokes, simplified forms, intense hues" },
    { id: 36, name: "Futurismo", category: "Tradicional", prompt: "futurist art, dynamic motion, speed lines, mechanical forms, bold energy" },
    { id: 37, name: "Dadaísmo", category: "Tradicional", prompt: "dada art, absurd compositions, anti-art aesthetic, random elements, provocative imagery" },
    { id: 38, name: "Constructivismo", category: "Tradicional", prompt: "constructivist art, geometric shapes, bold typography, red and black colors, propaganda style" },
    { id: 39, name: "Pop Art", category: "Tradicional", prompt: "pop art style, bright colors, comic book aesthetic, celebrity portraits, consumerism themes" },
    { id: 40, name: "Op Art", category: "Tradicional", prompt: "op art, optical illusions, geometric patterns, black and white, visual effects, kinetic energy" },

    // ESTILOS DE FOTOGRAFÍA (35)
    { id: 41, name: "Fotografía Realista", category: "Fotografía", prompt: "photorealistic, DSLR quality, sharp focus, natural lighting, high resolution, detailed textures" },
    { id: 42, name: "Retrato Cinematográfico", category: "Fotografía", prompt: "cinematic portrait, dramatic lighting, shallow depth of field, film grain, moody atmosphere" },
    { id: 43, name: "Fotografía Callejera", category: "Fotografía", prompt: "street photography, candid moments, urban environment, documentary style, natural light" },
    { id: 44, name: "Macro Fotografía", category: "Fotografía", prompt: "macro photography, extreme close-up, intricate details, shallow depth of field, textured surface" },
    { id: 45, name: "Fotografía Nocturna", category: "Fotografía", prompt: "night photography, long exposure, city lights, starry sky, ambient glow, dark atmosphere" },
    { id: 46, name: "Blanco y Negro", category: "Fotografía", prompt: "black and white photography, high contrast, dramatic shadows, monochrome, classic aesthetic" },
    { id: 47, name: "Vintage 70s", category: "Fotografía", prompt: "1970s photography, vintage aesthetic, warm tones, film grain, retro colors, nostalgic mood" },
    { id: 48, name: "Polaroid", category: "Fotografía", prompt: "polaroid photo, instant film, white border, faded colors, nostalgic aesthetic, square format" },
    { id: 49, name: "Fotografía de Moda", category: "Fotografía", prompt: "fashion photography, high fashion, studio lighting, elegant pose, glamorous aesthetic, editorial style" },
    { id: 50, name: "Fotografía Submarina", category: "Fotografía", prompt: "underwater photography, blue tones, floating particles, soft light rays, aquatic environment" },
    { id: 51, name: "HDR", category: "Fotografía", prompt: "HDR photography, enhanced dynamic range, vivid colors, detailed shadows and highlights, hyper-realistic" },
    { id: 52, name: "Tilt-Shift", category: "Fotografía", prompt: "tilt-shift photography, miniature effect, selective focus, toy-like appearance, aerial perspective" },
    { id: 53, name: "Lomografía", category: "Fotografía", prompt: "lomography, cross-processed colors, vignetting, light leaks, experimental photography" },
    { id: 54, name: "Infrarrojo", category: "Fotografía", prompt: "infrared photography, false color, white foliage, dark sky, surreal landscape" },
    { id: 55, name: "Doble Exposición", category: "Fotografía", prompt: "double exposure, overlapping images, dreamy blend, artistic composition, transparent layers" },
    { id: 56, name: "Fotografía Documental", category: "Fotografía", prompt: "documentary photography, photojournalism style, authentic moments, social commentary, natural light" },
    { id: 57, name: "Bokeh", category: "Fotografía", prompt: "bokeh effect, soft background blur, circular light spots, shallow depth of field, dreamy atmosphere" },
    { id: 58, name: "Golden Hour", category: "Fotografía", prompt: "golden hour lighting, warm sunset glow, soft shadows, magical atmosphere, golden tones" },
    { id: 59, name: "Blue Hour", category: "Fotografía", prompt: "blue hour photography, deep blue sky, twilight atmosphere, city lights, cool tones" },
    { id: 60, name: "Contraluz", category: "Fotografía", prompt: "backlit photography, silhouette, rim lighting, sun flare, dramatic contrast" },
    { id: 61, name: "Fotografía Aérea", category: "Fotografía", prompt: "aerial photography, bird's eye view, drone shot, geometric patterns, landscape overview" },
    { id: 62, name: "Fotografía de Producto", category: "Fotografía", prompt: "product photography, clean white background, studio lighting, professional quality, commercial style" },
    { id: 63, name: "Fotografía Arquitectónica", category: "Fotografía", prompt: "architectural photography, symmetrical composition, leading lines, wide angle, perspective correction" },
    { id: 64, name: "Fotografía de Naturaleza", category: "Fotografía", prompt: "nature photography, wildlife, natural environment, detailed textures, vibrant colors" },
    { id: 65, name: "Fotografía Minimalista", category: "Fotografía", prompt: "minimalist photography, negative space, simple composition, clean lines, limited elements" },
    { id: 66, name: "Cámara de Juguete", category: "Fotografía", prompt: "toy camera effect, lo-fi aesthetic, vignetting, soft focus, unpredictable colors" },
    { id: 67, name: "Fotografía de Estudio", category: "Fotografía", prompt: "studio photography, controlled lighting, seamless background, professional setup, clean aesthetic" },
    { id: 68, name: "Fotografía Deportiva", category: "Fotografía", prompt: "sports photography, action shot, fast shutter speed, motion blur, dynamic composition" },
    { id: 69, name: "Fotografía de Conciertos", category: "Fotografía", prompt: "concert photography, stage lighting, dramatic colors, motion blur, energetic atmosphere" },
    { id: 70, name: "Cine Negro", category: "Fotografía", prompt: "film noir style, high contrast black and white, venetian blind shadows, dramatic lighting, mystery mood" },
    { id: 71, name: "Daguerrotipo", category: "Fotografía", prompt: "daguerreotype, 19th century photography, sepia tones, aged aesthetic, vintage portrait style" },
    { id: 72, name: "Cianotipia", category: "Fotografía", prompt: "cyanotype print, prussian blue tones, sun printing technique, botanical subjects, vintage scientific aesthetic" },
    { id: 73, name: "Solarización", category: "Fotografía", prompt: "solarization effect, reversed tones, surreal appearance, psychedelic aesthetic, experimental photography" },
    { id: 74, name: "Fotografía Submarina", category: "Fotografía", prompt: "underwater photography, refracted light, blue tones, bubbles, marine life, fluid movement" },
    { id: 75, name: "Fotografía de Siluetas", category: "Fotografía", prompt: "silhouette photography, backlit subjects, dramatic contrast, minimal detail, artistic composition" },

    // ESTILOS DE ILUSTRACIÓN Y DISEÑO (35)
    { id: 76, name: "Anime", category: "Ilustración", prompt: "anime style, cel shading, vibrant colors, large expressive eyes, manga aesthetic, Japanese animation" },
    { id: 77, name: "Studio Ghibli", category: "Ilustración", prompt: "Studio Ghibli style, hand-painted aesthetic, soft colors, whimsical atmosphere, detailed backgrounds" },
    { id: 78, name: "Comic Americano", category: "Ilustración", prompt: "american comic book style, bold outlines, dynamic poses, action lines, speech bubbles, halftone dots" },
    { id: 79, name: "Manga", category: "Ilustración", prompt: "manga style, black and white, screentones, dynamic panel layout, expressive characters" },
    { id: 80, name: "Cartoon Disney", category: "Ilustración", prompt: "Disney animation style, rounded shapes, expressive faces, colorful, family-friendly aesthetic" },
    { id: 81, name: "Pixar 3D", category: "Ilustración", prompt: "Pixar 3D animation style, detailed textures, warm lighting, appealing character design, cinematic quality" },
    { id: 82, name: "Tim Burton", category: "Ilustración", prompt: "Tim Burton style, gothic aesthetic, striped patterns, elongated proportions, dark whimsical, quirky characters" },
    { id: 83, name: "Línea Clara", category: "Ilustración", prompt: "ligne claire style, clean outlines, flat colors, European comic aesthetic, Tintin inspired" },
    { id: 84, name: "Ilustración Editorial", category: "Ilustración", prompt: "editorial illustration, conceptual imagery, bold composition, limited color palette, thought-provoking" },
    { id: 85, name: "Ilustración Infantil", category: "Ilustración", prompt: "children's book illustration, soft colors, friendly characters, simple shapes, whimsical details" },
    { id: 86, name: "Art de Vidrio", category: "Ilustración", prompt: "stained glass art, colorful glass pieces, lead lines, luminous colors, gothic windows" },
    { id: 87, name: "Pixel Art", category: "Ilustración", prompt: "pixel art, 8-bit style, retro gaming aesthetic, limited color palette, blocky forms" },
    { id: 88, name: "Vector Art", category: "Ilustración", prompt: "vector illustration, clean lines, flat colors, geometric shapes, scalable graphics, modern design" },
    { id: 89, name: "Isométrico", category: "Ilustración", prompt: "isometric art, 3D perspective, geometric precision, clean lines, technical illustration" },
    { id: 90, name: "Dibujo Técnico", category: "Ilustración", prompt: "technical drawing, blueprint style, precise lines, engineering aesthetic, detailed schematics" },
    { id: 91, name: "Caricatura", category: "Ilustración", prompt: "caricature style, exaggerated features, humorous portrayal, bold lines, simplified forms" },
    { id: 92, name: "Graffiti", category: "Ilustración", prompt: "graffiti art, spray paint aesthetic, bold colors, urban style, wild style lettering, street art" },
    { id: 93, name: "Tatuaje Tradicional", category: "Ilustración", prompt: "traditional tattoo style, bold outlines, limited color palette, classic motifs, american traditional" },
    { id: 94, name: "Art Naïf", category: "Ilustración", prompt: "naive art, childlike simplicity, bright colors, flat perspective, folk art aesthetic" },
    { id: 95, name: "Ilustración Botánica", category: "Ilustración", prompt: "botanical illustration, scientific accuracy, detailed plant structures, watercolor style, vintage natural history" },
    { id: 96, name: "Steampunk", category: "Ilustración", prompt: "steampunk art, victorian era, brass and copper, gears and machinery, retro-futuristic, industrial aesthetic" },
    { id: 97, name: "Chibi", category: "Ilustración", prompt: "chibi style, super deformed, cute proportions, large head, small body, kawaii aesthetic" },
    { id: 98, name: "Papercraft", category: "Ilustración", prompt: "papercraft style, cut paper layers, dimensional shadows, crafted appearance, paper texture" },
    { id: 99, name: "Origami", category: "Ilustración", prompt: "origami art, folded paper aesthetic, geometric folds, minimalist design, Japanese paper art" },
    { id: 100, name: "Silueta", category: "Ilustración", prompt: "silhouette art, solid black shapes, minimal detail, elegant simplicity, contrast against background" },
    { id: 101, name: "Ilustración Noir", category: "Ilustración", prompt: "noir illustration, high contrast, dramatic shadows, limited color palette, detective aesthetic" },
    { id: 102, name: "Acuarela Digital", category: "Ilustración", prompt: "digital watercolor, soft edges, transparent layers, flowing colors, painterly textures" },
    { id: 103, name: "Arte Lineal", category: "Ilustración", prompt: "line art, continuous lines, no shading, clean contours, minimalist drawing, ink style" },
    { id: 104, name: "Doodle", category: "Ilustración", prompt: "doodle art, hand-drawn, playful sketches, organic lines, casual aesthetic, pattern filled" },
    { id: 105, name: "Monotipo", category: "Ilustración", prompt: "monotype print, unique impressions, painterly quality, loose edges, artistic printing technique" },
    { id: 106, name: "Art Brut", category: "Ilustración", prompt: "art brut, raw art, outsider art aesthetic, untrained style, primitive expression, intense emotion" },
    { id: 107, name: "Lettering", category: "Ilustración", prompt: "hand lettering, decorative typography, flourishes, custom letterforms, calligraphic elements" },
    { id: 108, name: "Infografía", category: "Ilustración", prompt: "infographic style, data visualization, icons and symbols, clean layout, educational design" },
    { id: 109, name: "Ilustración de Moda", category: "Ilustración", prompt: "fashion illustration, elongated figures, stylized clothing, elegant lines, runway aesthetic" },
    { id: 110, name: "Concept Art", category: "Ilustración", prompt: "concept art, detailed environment design, production art style, cinematic lighting, matte painting quality" },

    // ESTILOS 3D Y RENDER (30)
    { id: 111, name: "Render Fotorrealista", category: "3D Render", prompt: "photorealistic 3D render, octane render, ray tracing, volumetric lighting, ultra detailed, 8K resolution" },
    { id: 112, name: "Clay Render", category: "3D Render", prompt: "clay render, matte material, monochrome, sculptural forms, soft lighting, production design" },
    { id: 113, name: "Low Poly", category: "3D Render", prompt: "low poly 3D, geometric facets, minimal polygons, flat shading, game art aesthetic" },
    { id: 114, name: "Voxel Art", category: "3D Render", prompt: "voxel art, 3D pixels, blocky forms, minecraft aesthetic, cubic shapes, retro 3D" },
    { id: 115, name: "Toon Shader", category: "3D Render", prompt: "toon shader, cel shaded 3D, cartoon outlines, flat colors, anime rendering style" },
    { id: 116, name: "Wireframe", category: "3D Render", prompt: "wireframe 3D, line mesh, technical visualization, glowing edges, cybernetic aesthetic" },
    { id: 117, name: "Cristal", category: "3D Render", prompt: "crystal render, transparent materials, light refraction, glossy surface, gem-like quality" },
    { id: 118, name: "Metal Pulido", category: "3D Render", prompt: "polished metal, chrome finish, mirror reflections, metallic shader, industrial aesthetic" },
    { id: 119, name: "Holográfico", category: "3D Render", prompt: "holographic effect, iridescent colors, rainbow sheen, futuristic aesthetic, tech interface" },
    { id: 120, name: "Neón", category: "3D Render", prompt: "neon lights, glowing edges, cyberpunk aesthetic, vibrant colors, futuristic cityscape" },
    { id: 121, name: "Render Arquitectónico", category: "3D Render", prompt: "architectural visualization, photorealistic interior, modern design, clean lines, professional rendering" },
    { id: 122, name: "Subsurface Scattering", category: "3D Render", prompt: "subsurface scattering, translucent materials, light diffusion, realistic skin, wax-like quality" },
    { id: 123, name: "Partículas", category: "3D Render", prompt: "particle system, dynamic simulation, fluid motion, smoke and fire effects, cinematic FX" },
    { id: 124, name: "Fur y Pelo", category: "3D Render", prompt: "fur rendering, realistic hair, strand-based simulation, detailed texture, natural movement" },
    { id: 125, name: "Volumétrico", category: "3D Render", prompt: "volumetric rendering, god rays, atmospheric fog, light beams, cinematic depth" },
    { id: 126, name: "PBR Materials", category: "3D Render", prompt: "PBR materials, physically based rendering, realistic textures, metallic and roughness maps" },
    { id: 127, name: "Procedural", category: "3D Render", prompt: "procedural generation, algorithmic patterns, mathematical forms, fractal geometry, organic structures" },
    { id: 128, name: "Plastilina", category: "3D Render", prompt: "claymation style, stop motion aesthetic, clay texture, handcrafted look, Wallace and Gromit style" },
    { id: 129, name: "Mármol", category: "3D Render", prompt: "marble material, veined patterns, polished stone, classical sculpture aesthetic, white and gold" },
    { id: 130, name: "Madera", category: "3D Render", prompt: "wood texture, grain patterns, natural material, warm tones, carved details" },
    { id: 131, name: "Tela y Textil", category: "3D Render", prompt: "fabric simulation, cloth dynamics, textile patterns, soft materials, realistic draping" },
    { id: 132, name: "Líquido", category: "3D Render", prompt: "liquid simulation, fluid dynamics, water splash, reflective surface, realistic physics" },
    { id: 133, name: "Cristal Roto", category: "3D Render", prompt: "shattered glass, fractured patterns, sharp fragments, destruction effect, crystalline pieces" },
    { id: 134, name: "Nieve", category: "3D Render", prompt: "snow material, icy texture, winter scene, crystalline surface, cold atmosphere" },
    { id: 135, name: "Caucho", category: "3D Render", prompt: "rubber material, matte finish, soft appearance, flexible forms, toy-like quality" },
    { id: 136, name: "Plástico Brillante", category: "3D Render", prompt: "glossy plastic, vibrant colors, toy aesthetic, shiny surface, commercial product style" },
    { id: 137, name: "Cemento", category: "3D Render", prompt: "concrete texture, brutalist aesthetic, rough surface, industrial design, gray tones" },
    { id: 138, name: "Oro y Joyas", category: "3D Render", prompt: "gold material, jewelry rendering, precious gems, luxurious aesthetic, sparkling highlights" },
    { id: 139, name: "Caramelo", category: "3D Render", prompt: "candy material, translucent sweets, glossy surface, vibrant colors, whimsical food design" },
    { id: 140, name: "Burbujas", category: "3D Render", prompt: "soap bubbles, iridescent surface, transparent spheres, light refraction, delicate forms" },

    // ESTILOS CINEMATOGRÁFICOS Y VIDEOJUEGOS (25)
    { id: 141, name: "Blade Runner", category: "Cinematográfico", prompt: "blade runner aesthetic, cyberpunk cityscape, neon lights, rain-soaked streets, dystopian future" },
    { id: 142, name: "Mad Max", category: "Cinematográfico", prompt: "mad max style, post-apocalyptic, desert wasteland, rusty vehicles, survival aesthetic" },
    { id: 143, name: "Matrix", category: "Cinematográfico", prompt: "matrix style, digital rain, green tint, cyberpunk aesthetic, reality distortion" },
    { id: 144, name: "Star Wars", category: "Cinematográfico", prompt: "star wars aesthetic, space opera, alien planets, sci-fi technology, epic scale" },
    { id: 145, name: "Wes Anderson", category: "Cinematográfico", prompt: "wes anderson style, symmetrical composition, pastel colors, centered framing, quirky details" },
    { id: 146, name: "Christopher Nolan", category: "Cinematográfico", prompt: "christopher nolan cinematography, imax quality, dramatic lighting, realistic effects, epic scale" },
    { id: 147, name: "Horror Gótico", category: "Cinematográfico", prompt: "gothic horror, dark atmosphere, victorian architecture, eerie lighting, supernatural elements" },
    { id: 148, name: "Western", category: "Cinematográfico", prompt: "western film style, desert landscape, warm sepia tones, dusty atmosphere, frontier aesthetic" },
    { id: 149, name: "Ciencia Ficción Retro", category: "Cinematográfico", prompt: "retro sci-fi, 1950s futurism, chrome rockets, atomic age aesthetic, pulp magazine style" },
    { id: 150, name: "Noir Cyberpunk", category: "Cinematográfico", prompt: "cyberpunk noir, neon reflections, rain-soaked city, high tech low life, blade runner inspired" },
    { id: 151, name: "Fantasía Épica", category: "Cinematográfico", prompt: "epic fantasy, medieval castles, dragons, magical atmosphere, lord of the rings inspired" },
    { id: 152, name: "Superhéroes", category: "Cinematográfico", prompt: "superhero movie style, dynamic action, heroic poses, dramatic lighting, comic book inspired" },
    { id: 153, name: "Thriller Psicológico", category: "Cinematográfico", prompt: "psychological thriller, unsettling atmosphere, muted colors, suspenseful composition" },
    { id: 154, name: "Videojuego 8-bit", category: "Videojuegos", prompt: "8-bit game graphics, pixel art, limited colors, retro gaming, NES aesthetic" },
    { id: 155, name: "Videojuego 16-bit", category: "Videojuegos", prompt: "16-bit game graphics, SNES style, detailed sprites, vibrant colors, classic gaming" },
    { id: 156, name: "PlayStation 1", category: "Videojuegos", prompt: "PS1 graphics, low poly 3D, texture warping, early 3D gaming aesthetic, nostalgic" },
    { id: 157, name: "Cel-Shading Game", category: "Videojuegos", prompt: "cel-shaded video game, toon shader, comic book outlines, zelda wind waker style" },
    { id: 158, name: "RPG Isométrico", category: "Videojuegos", prompt: "isometric RPG, tactical view, detailed environments, classic RPG aesthetic" },
    { id: 159, name: "Survival Horror", category: "Videojuegos", prompt: "survival horror game, dark corridors, limited lighting, tense atmosphere, resident evil style" },
    { id: 160, name: "Battle Royale", category: "Videojuegos", prompt: "battle royale game, large map, military aesthetic, fortnite/pubg style, competitive gaming" },
    { id: 161, name: "MMORPG", category: "Videojuegos", prompt: "MMORPG style, fantasy world, detailed characters, magical effects, world of warcraft inspired" },
    { id: 162, name: "Fighting Game", category: "Videojuegos", prompt: "fighting game, dynamic poses, special effects, arcade aesthetic, street fighter style" },
    { id: 163, name: "Platformer", category: "Videojuegos", prompt: "platformer game, colorful levels, collect items, mario-style, side-scrolling view" },
    { id: 164, name: "Sandbox Game", category: "Videojuegos", prompt: "sandbox game, open world, building mechanics, minecraft aesthetic, creative gameplay" },
    { id: 165, name: "Racing Game", category: "Videojuegos", prompt: "racing game, sleek vehicles, motion blur, track environment, gran turismo style" },

    // ESTILOS EXPERIMENTALES Y ABSTRACTOS (20)
    { id: 166, name: "Glitch Art", category: "Experimental", prompt: "glitch art, digital corruption, distorted pixels, RGB shift, corrupted data aesthetic" },
    { id: 167, name: "Vaporwave", category: "Experimental", prompt: "vaporwave aesthetic, retro 90s, pastel colors, greek statues, palm trees, nostalgic internet" },
    { id: 168, name: "Synthwave", category: "Experimental", prompt: "synthwave, neon grid, sunset colors, 80s aesthetic, retro futuristic, outrun style" },
    { id: 169, name: "Cyberdelic", category: "Experimental", prompt: "cyberdelic art, psychedelic colors, digital patterns, fractal geometry, trippy visuals" },
    { id: 170, name: "Glitchcore", category: "Experimental", prompt: "glitchcore, chaotic composition, bright colors, text overlays, internet culture aesthetic" },
    { id: 171, name: "Weirdcore", category: "Experimental", prompt: "weirdcore, liminal spaces, unsettling atmosphere, nostalgic yet eerie, dreamcore elements" },
    { id: 172, name: "Dreamcore", category: "Experimental", prompt: "dreamcore, surreal imagery, soft focus, nostalgic feelings, dreamy atmosphere, childhood memories" },
    { id: 173, name: "Acidwave", category: "Experimental", prompt: "acidwave, psychedelic colors, melting forms, trippy patterns, rave aesthetic" },
    { id: 174, name: "Fractal", category: "Experimental", prompt: "fractal art, recursive patterns, mandelbrot set, infinite complexity, mathematical beauty" },
    { id: 175, name: "Abstracto Geométrico", category: "Experimental", prompt: "geometric abstract, colorful shapes, mathematical precision, bauhaus inspired, modern composition" },
    { id: 176, name: "Expresionismo Abstracto", category: "Experimental", prompt: "abstract expressionism, gestural brushstrokes, emotional intensity, jackson pollock style, drip painting" },
    { id: 177, name: "Minimalismo Abstracto", category: "Experimental", prompt: "abstract minimalism, simple forms, limited colors, clean composition, rothko inspired" },
    { id: 178, name: "Arte Generativo", category: "Experimental", prompt: "generative art, algorithmic patterns, mathematical rules, computational aesthetics, random elements" },
    { id: 179, name: "Arte de Datos", category: "Experimental", prompt: "data art, information visualization, abstract data patterns, infographic aesthetic, technological" },
    { id: 180, name: "Chromatic Aberration", category: "Experimental", prompt: "chromatic aberration, RGB split, color fringing, lens distortion effect, glitchy aesthetic" },
    { id: 181, name: "Surrealismo Digital", category: "Experimental", prompt: "digital surrealism, impossible geometry, dreamlike combinations, photobashing, avant-garde" },
    { id: 182, name: "Biomecánico", category: "Experimental", prompt: "biomechanical art, H.R. Giger style, organic and mechanical fusion, alien aesthetic, dark surrealism" },
    { id: 183, name: "Psicodélico", category: "Experimental", prompt: "psychedelic art, kaleidoscopic patterns, vibrant colors, mind-bending visuals, 60s inspired" },
    { id: 184, name: "Maximalismo", category: "Experimental", prompt: "maximalist art, highly detailed, dense composition, ornate decoration, visual abundance" },
    { id: 185, name: "Neo-Futurismo", category: "Experimental", prompt: "neo-futurism, sleek architecture, organic curves, advanced technology, utopian vision" },

    // ESTILOS CULTURALES Y ESPECÍFICOS (15)
    { id: 186, name: "Azteca/Maya", category: "Cultural", prompt: "aztec maya art, pre-columbian patterns, geometric symbols, ancient mesoamerican aesthetic, stone carvings" },
    { id: 187, name: "Egipcio", category: "Cultural", prompt: "ancient egyptian art, hieroglyphics, profile view figures, gold and lapis lazuli, papyrus style" },
    { id: 188, name: "Celta", category: "Cultural", prompt: "celtic art, intricate knotwork, spirals and triskeles, illuminated manuscripts, medieval irish style" },
    { id: 189, name: "Nórdico Vikingo", category: "Cultural", prompt: "norse viking art, runes and symbols, interlaced patterns, mythology themes, wood carving style" },
    { id: 190, name: "Indio Mughal", category: "Cultural", prompt: "mughal indian art, intricate miniatures, persian influence, rich colors, ornate patterns" },
    { id: 191, name: "Africano Tribal", category: "Cultural", prompt: "african tribal art, geometric patterns, bold colors, mask designs, traditional crafts" },
    { id: 192, name: "Aborigen Australiano", category: "Cultural", prompt: "aboriginal dot painting, dreamtime stories, earth tones, symbolic patterns, indigenous australian art" },
    { id: 193, name: "Maorí", category: "Cultural", prompt: "maori art, ta moko patterns, spirals and curves, tribal designs, new zealand indigenous" },
    { id: 194, name: "Asiático Zen", category: "Cultural", prompt: "zen asian art, minimalist composition, ink wash, bamboo motifs, meditative aesthetic" },
    { id: 195, name: "Art Deco Chino", category: "Cultural", prompt: "chinese art deco, shanghai style, geometric patterns with eastern motifs, luxury aesthetic" },
    { id: 196, name: "Tropical Tiki", category: "Cultural", prompt: "tiki art, polynesian masks, tropical colors, bamboo textures, vintage hawaiian style" },
    { id: 197, name: "Día de Muertos", category: "Cultural", prompt: "dia de los muertos, sugar skulls, vibrant colors, marigold flowers, mexican folk art" },
    { id: 198, name: "Folk Ruso", category: "Cultural", prompt: "russian folk art, matryoshka dolls, khokhloma patterns, bright colors, traditional painting" },
    { id: 199, name: "Art Nouveau Japonés", category: "Cultural", prompt: "japanese art nouveau, mixing ukiyo-e with western curves, elegant florals, mucha meets hokusai" },
    { id: 200, name: "Sumi-e", category: "Cultural", prompt: "sumi-e ink painting, minimalist brushstrokes, zen aesthetic, black ink on white, japanese calligraphy" }
  ];